[theme]
base="light"
primaryColor="#fb6a00"
backgroundColor="#d1e6ff"
secondaryBackgroundColor="#9fcbff"
[theme]
base="light"
primaryColor="#fb6a00"
backgroundColor="#edf3f9"
secondaryBackgroundColor="#b2d6fb"
